### PR TITLE
Form templates revamp

### PR DESCRIPTION
**Pull request by dominic-blain**
This is in no way finished work. I'm opening this PR right now to get feedback earlier and to make the work available to anyone who wants to work on it and/or update corresponding JS modules and components. 

The goal is to facilitate the creation and reusability of form styles by having templates for specific fields instead of converging all of them into one (form-control). Redundancy could be reduced after real life testing (looking at fiels like text, password and email, just to name a few) but ease of modification should be prioritized before DRYness (or let's use solutions other than cramming too much options into a single template, like recipes).

In a project, we would use styled form components (_à la site-form-field,_ but without the structure restriction). These styled forms could be packaged and chosen from in the design phase instead of reinventing the wheel each time.

This PR aims to work with the recent _form-dyn.js_ update and will require a rework of _form.js_ and _form-field.js_. A new _start.sql_ including normalized form sections would also be a nice addition.

Fields that should be included in this PR:
- [X] Checkbox
- [ ] Email
- [X] File
- [X] Number
- [ ] Password
- [X] Radio
- [ ] Submit
- [ ] Tel
- [X] Text
- [X] Select
- [X] Option
- [X] Textarea
- [X] List (checkbox or radio)

Fields that could be added later on:

- Datalist
- Color
- Date
- Hidden
- Range
- Search
- Opt Group

### CODE REVIEW

**Comment by dominic-blain** [comment]
I have made a few more field types that I'd like to commit before but yeah I'm all for merge earlier!

**Comment by dominic-blain** [comment]
@nitriques I pushed two new fields (number and file) with some upgrades to most of the others. We can merge this and start building on it! 👯‍♂️

**Comment by nitriques** [comment]
damn big PRs, so hard to review, so hard to rebase...

@dominic-blain how do you want to handle it ?

**Comment by dominic-blain** [comment]
I basically deleted all existing form fields and started with a blank slate. At this point I would completely override old files with this PR and fix problems that might arise in other PRs after testing them more.

**Comment by nitriques** [comment]
@dominic-blain Can we agree to at least remove stuff that do not exists ?

Also, it needs serious rebase... sorry.

**Comment by dominic-blain** [comment]
@nitriques @PascalPiche Removed inexistant classes and used set where appropriate

**Comment by dominic-blain** [comment]
@PascalPiche Ping? :)

**Comment by dominic-blain** [comment]
@PascalPiche Pong

**Pull request merged**
