### PR TITLE
Added a bunch of schema i'm generaly using

### PR DESCRIPTION
**Pull request by hotdoy**
Figured it could save some time.

### CODE REVIEW

**Comment by fhamon** [comment]
@hotdoy You closed it ?

**Comment by hotdoy** [comment]
I messed up.
But I did another pr with the new meta tag values so its in there somewhere.

**Comment by nitriques** [comment]
The other PR mixes too many things. Want me to merge this one ? @fhamon @hotdoy ?

**Comment by hotdoy** [comment]
Yeah. Why not. 
I'll split the other one in smaller bits.

**Comment by nitriques** [comment]
@hotdoy Your branches are all mixed up. You would need to:

1. Create a new `temp-dev` branch from your current dev.
2. Trash your local `master` and `dev`: make sure they sync up to the our remote.
3. Create new PRs from a new feature brach, which could cherry-pick the commits in `temp-dev`.

I'll cherry pick e0371fdf5364df50dc4bd60dfcddd36f65c33cb4 for now.

**Comment by nitriques** [comment]
Picked as 43c21a5081 in #261

**Pull request closed without merging**
