### PR TITLE
Remove dev tool from build. Clean everything before the build.

### PR DESCRIPTION
**Pull request by PascalPiche**

### CODE REVIEW

**Comment by PascalPiche** [comment]
Some dev tools like the deprecated function was leaking in prod.

**Comment by nitriques** [comment]
Ok, but how? And why do we need to clean the css and less ?

**Comment by PascalPiche** [comment]
we have a task to concat all the lib and to generate lib.css  If we dont clean the folder before the build. the concat will concat the css file with the less file and the css file was generated with the debug flag to true and bring dev tools in prod with duplicated rules.

**Comment by nitriques** [comment]
So there would be no problem if we'd list the files instead of taking the whole directory ?
And now, your change moves the fct-dev file into the dev folder and requiring it. That's cool. But I do not get why we need to delete the css files.

**Comment by nitriques** [comment]
So our final decision was to 1) ignore the file in svn and 2) change the default build to clean less and css (keep those as separate targets) amirite ?

**Pull request merged**
